// USER CONTEXT
export const GET_LOGGED_IN_USER = 'GET_LOGGED_IN_USER'
export const CLEAR_LOGGED_IN_USER = 'CLEAR_LOGGED_IN_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const AUTH_FAILED = 'AUTH_FAILED'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// NAV CONTEXT
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_LOADING = 'SET_LOADING'

// USER CONTEXT
export const GET_SELECTED_USER = 'GET_SELECTED_USER'
export const CLEAR_SELECTED_USER = 'CLEAR_SELECTED_USER'

// POST CONTEXT
export const GET_USER_POSTS = 'GET_UESR_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_DASHBOARD_POSTS = 'GET_DASHBOARD_POSTS'
export const SUBMIT_POST = 'SUBMIT_POST'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const SET_DELETE_MODAL = 'SET_DELETE_MODAL'
export const CLEAR_DELETE_MODAL = 'CLEAR_DELETE_MODAL'
