// USER CONTEXT
export const GET_LOGGED_IN_USER = 'GET_LOGGED_IN_USER'
export const CLEAR_LOGGED_IN_USER = 'CLEAR_LOGGED_IN_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const AUTH_FAILED = 'AUTH_FAILED'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// NAV CONTEXT
export const SET_ACTIVE ='SET_ACTIVE'

// USER CONTEXT
export const GET_SELECTED_USER='GET_SELECTED_USER'
export const CLEAR_SELECTED_USER='CLEAR_SELECTED_USER'
